global:
  sendAnonymousUsage: false

providers:
  docker:
    exposedByDefault: false
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
  file:
    directory: /etc/traefik/conf/
    watch: true

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"